### ISSUE TITLE
Feature request: mailing list

### ISSUE THREAD

**Issue by smiile8888** [saladpuk/gitbook#6]
พึ่งเข้ามาติดตาม ชอบเนื้อหาและการนำเสนอมากค่ะ เข้าใจง่ายมีภาพประกอบ
อยากเสนอเพิ่มเติมหากมี mailing list/subscribe feature น่าจะเป็นประโยชน์สำหรับคนติดตามและตัวเว็บไซต์ค่ะ

ขอบคุณที่นำเสนอสาระดี ๆ ให้กันนะค่ะ 😃

**Comment by Sakul** [comment]
ขอบคุณมากครับ อยากจะทำเหมือนกันแต่ตัวเว็บสลัดผักผมใช้ของสำเร็จรูป + ไม่มีเวลาทำเอง ถ้าสนใจ subscribe เบื้องต้นก็กดที่ github นี้ได้เลยครับ 🤣
